//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguagePack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagePack() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HAI.Resources.Languages.LanguagePack", typeof(LanguagePack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ai.
        /// </summary>
        public static string Ai {
            get {
                return ResourceManager.GetString("Ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ai knowledge:.
        /// </summary>
        public static string AiKnowledge {
            get {
                return ResourceManager.GetString("AiKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ai wins.
        /// </summary>
        public static string AiWins {
            get {
                return ResourceManager.GetString("AiWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averege wins:.
        /// </summary>
        public static string AverageWins {
            get {
                return ResourceManager.GetString("AverageWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game info.
        /// </summary>
        public static string GameInfo {
            get {
                return ResourceManager.GetString("GameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player wins.
        /// </summary>
        public static string PlayerWins {
            get {
                return ResourceManager.GetString("PlayerWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ai knowledge.
        /// </summary>
        public static string PlotTitle {
            get {
                return ResourceManager.GetString("PlotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats info.
        /// </summary>
        public static string StatsInfo {
            get {
                return ResourceManager.GetString("StatsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose pawn to move.
        /// </summary>
        public static string Tutorial1 {
            get {
                return ResourceManager.GetString("Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forward if cell is empty.
        /// </summary>
        public static string Tutorial2 {
            get {
                return ResourceManager.GetString("Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for opponent move.
        /// </summary>
        public static string Tutorial3 {
            get {
                return ResourceManager.GetString("Tutorial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose pawn to move.
        /// </summary>
        public static string Tutorial4 {
            get {
                return ResourceManager.GetString("Tutorial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move diagonally and take opponent pawn.
        /// </summary>
        public static string Tutorial5 {
            get {
                return ResourceManager.GetString("Tutorial5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won!.
        /// </summary>
        public static string Tutorial6 {
            get {
                return ResourceManager.GetString("Tutorial6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victories.
        /// </summary>
        public static string Victories {
            get {
                return ResourceManager.GetString("Victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
    }
}
